# Project information
site_name: Nakama Server
site_description: Documentation for the Nakama realtime and social server for games and apps.
site_author: Heroic Labs Team & Contributors
site_url: https://heroiclabs.com/
edit_uri: https://github.com/heroiclabs/nakama-docs/edit/master/docs/

# Deployment
remote_name: origin
remote_branch: gh-pages

# Repository
repo_name: heroiclabs/nakama
repo_url: https://github.com/heroiclabs/nakama

# Copyright
copyright: Copyright &copy; 2021 Heroic Labs

# Documentation and theme
theme:
  name: material
  language: en
  logo: images/logo-white.svg
  favicon: images/favicon.ico
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - navigation.top
    # Top level navigation turned into tabs
    # Use to implement Nakama Docs Realms
    # - navigation.tabs

extra_javascript:
  - javascripts/main.js

extra_css:
  - css/extra.css

# Options
plugins:
  - search:
      lang:
        - en

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://heroiclabs.com
    - icon: fontawesome/brands/github
      link: https://github.com/heroiclabs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/heroicdev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/heroic-labs

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: False
      guess_lang: False
  - toc:
      permalink: True
  - pymdownx.superfences
  - pymdownx.tabbed

# Nav menu
nav:
  - Getting Started:
    - Introduction: index.md
    - Docker compose: install-docker-quickstart.md
    - Windows binary: install-binary-windows-quickstart.md
    - macOS binary: install-binary-macos-quickstart.md
    - Linux binary: install-binary-linux-quickstart.md
    - Nakama CLI: install-server-cli.md
    - Configuration: install-configuration.md
    - Upgrading Nakama: install-nakama-upgrade.md
    - Nakama Console: console-overview.md
  - Client Libraries:
    - .NET/Unity: unity-client-guide.md
    - JavaScript: javascript-client-guide.md
    - Godot: godot-client-guide.md
    - Defold : defold-client-guide.md
    - Java/Android: android-java-client-guide.md
    - C++: cpp-client-guide.md
    - Unreal: unreal-client-guide.md
    - Cocos2d-x C++: cocos2d-x-client-guide.md
    - Cocos2d-x JS: cocos2d-x-js-client-guide.md
  - Features:
    - User Accounts:
      - Authentication: authentication.md
      - User accounts: user-accounts.md
      - Initialize a new user: tutorial-initialize-new-user.md
      - Sessions: session.md
      - Session management: expert-auth.md
    - Storage Engine:
      - Collections: storage-collections.md
      - Access controls: storage-access-controls.md
    - Friends: social-friends.md
    - Groups and Clans: social-groups-clans.md
    - In-app Notifications: social-in-app-notifications.md
    - Status: social-status.md
    - Realtime Chat: social-realtime-chat.md
    - Leaderboards: gameplay-leaderboards.md
    - Tournaments: gameplay-tournaments.md
    - Matchmaker: gameplay-matchmaker.md
    - Realtime Multiplayer: gameplay-multiplayer-realtime.md
    - Authoritative Multiplayer: gameplay-multiplayer-server-multiplayer.md
    - IAP Validation: iap-validation.md
  - Server Runtime Code:
    - Basics: runtime-code-basics.md
    - TypeScript Setup: runtime-code-typescript-setup.md
    - Function Reference: runtime-code-function-reference.md
  - Advanced:
    - Events: advanced-events.md
    - Streams: advanced-streams.md
    - Push messages: tutorial-send-push-messages.md
    - Choosing TCP or UDP: expert-tcp-udp.md
    - Modelling for Scalability: expert-modelling.md
    - Remote configuration: tutorial-remote-configuration.md
    - Develop with LibGDX: tutorial-develop-with-libgdx.md
    - Deploy to Digital Ocean: deployment-digital-ocean.md
    - Previous releases: previous-versions.md
  - Benchmarks: benchmarks.md
